import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import StoreProvide from "./StoreProvide";
import GlobalDataProvide from "./components/GlobalDataProvide";

import LayoutWrapper from "./components/LayoutWrapper";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <StoreProvide>
          <GlobalDataProvide>
            <LayoutWrapper>
            {children}
            </LayoutWrapper>
          </GlobalDataProvide>
        </StoreProvide>
      </body>
    </html>
  );
}
